


<?php
$newCarBrands = [
    ['id' => 1, 'name' => 'Toyota', 'imageURL' => 'assets/img/brand-imgs/Toyota.png'],
    ['id' => 2, 'name' => 'BMW', 'imageURL' => 'assets/img/brand-imgs/BMW.png'],
    ['id' => 3, 'name' => 'Chevrolet', 'imageURL' => 'assets/img/brand-imgs/Chevrolet.png'],
    ['id' => 4, 'name' => 'Honda', 'imageURL' => 'assets/img/brand-imgs/Honda.png'],
    ['id' => 5, 'name' => 'Ford', 'imageURL' => 'assets/img/brand-imgs/Ford.png'],
    ['id' => 6, 'name' => 'Audi', 'imageURL' => 'assets/img/brand-imgs/Audi.png'],
    ['id' => 7, 'name' => 'Acura', 'imageURL' => 'assets/img/brand-imgs/Acura.png'],
    ['id' => 8, 'name' => 'Hyundai', 'imageURL' => 'assets/img/brand-imgs/Hyundai.png'],
    ['id' => 9, 'name' => 'Dodge', 'imageURL' => 'assets/img/brand-imgs/Dodge.png'],
    ['id' => 10, 'name' => 'Mercedes-Benz', 'imageURL' => 'assets/img/brand-imgs/Mercedes-Benz.png'],
    ['id' => 11, 'name' => 'Kia', 'imageURL' => 'assets/img/brand-imgs/Kia.png'],
    ['id' => 12, 'name' => 'Lexus', 'imageURL' => 'assets/img/brand-imgs/Lexus.png']
];

$usedCarBrands = [
    ['id' => 1, 'name' => 'Toyota', 'imageURL' => 'assets/img/brand-imgs/Toyota.png'],
    ['id' => 2, 'name' => 'BMW', 'imageURL' => 'assets/img/brand-imgs/BMW.png'],
    ['id' => 3, 'name' => 'Chevrolet', 'imageURL' => 'assets/img/brand-imgs/Chevrolet.png'],
    ['id' => 4, 'name' => 'Honda', 'imageURL' => 'assets/img/brand-imgs/Honda.png'],
    ['id' => 5, 'name' => 'Ford', 'imageURL' => 'assets/img/brand-imgs/Ford.png'],
    ['id' => 6, 'name' => 'Audi', 'imageURL' => 'assets/img/brand-imgs/Audi.png'],
    ['id' => 7, 'name' => 'Acura', 'imageURL' => 'assets/img/brand-imgs/Acura.png'],
    ['id' => 8, 'name' => 'Hyundai', 'imageURL' => 'assets/img/brand-imgs/Hyundai.png'],
    ['id' => 9, 'name' => 'Dodge', 'imageURL' => 'assets/img/brand-imgs/Dodge.png'],
    ['id' => 10, 'name' => 'Mercedes-Benz', 'imageURL' => 'assets/img/brand-imgs/Mercedes-Benz.png'],
    ['id' => 11, 'name' => 'Kia', 'imageURL' => 'assets/img/brand-imgs/Kia.png'],
    ['id' => 12, 'name' => 'Lexus', 'imageURL' => 'assets/img/brand-imgs/Lexus.png']
];

$showNewCars = [
    ['id' => 1, 'name' => 'Acura', 'imageURL' => 'assets/img/brand-imgs/Acura.png'],
    ['id' => 2, 'name' => 'Alfa Romeo', 'imageURL' => 'assets/img/brand-imgs/Alfa_Romeo.png'],
    ['id' => 3, 'name' => 'Audi', 'imageURL' => 'assets/img/brand-imgs/Audi.png'],
    ['id' => 4, 'name' => 'BMW', 'imageURL' => 'assets/img/brand-imgs/BMW.png'],
    ['id' => 5, 'name' => 'Buick', 'imageURL' => 'assets/img/brand-imgs/Buick.png'],
    ['id' => 6, 'name' => 'Cadillac', 'imageURL' => 'assets/img/brand-imgs/Cadillac.png'],
    ['id' => 7, 'name' => 'Chevrolet', 'imageURL' => 'assets/img/brand-imgs/Chevrolet.png'],
    ['id' => 8, 'name' => 'Chrysler', 'imageURL' => 'assets/img/brand-imgs/Chrysler.png'],
    ['id' => 9, 'name' => 'Dodge', 'imageURL' => 'assets/img/brand-imgs/Dodge.png'],
    ['id' => 10, 'name' => 'FIAT', 'imageURL' => 'assets/img/brand-imgs/FIAT.png'],
    ['id' => 11, 'name' => 'Ford', 'imageURL' => 'assets/img/brand-imgs/Ford.png'],
    ['id' => 12, 'name' => 'Genesis', 'imageURL' => 'assets/img/brand-imgs/Genesis.png'],
    ['id' => 13, 'name' => 'GMC', 'imageURL' => 'assets/img/brand-imgs/GMC.png'],
    ['id' => 14, 'name' => 'Honda', 'imageURL' => 'assets/img/brand-imgs/Honda.png'],
    ['id' => 15, 'name' => 'Hyundai', 'imageURL' => 'assets/img/brand-imgs/Hyundai.png'],
    ['id' => 16, 'name' => 'INFINITI', 'imageURL' => 'assets/img/brand-imgs/INFINITI.png'],
    ['id' => 17, 'name' => 'Jaguar', 'imageURL' => 'assets/img/brand-imgs/Jaguar.png'],
    ['id' => 18, 'name' => 'Jeep', 'imageURL' => 'assets/img/brand-imgs/Jeep.png'],
    ['id' => 19, 'name' => 'Kia', 'imageURL' => 'assets/img/brand-imgs/Kia.png'],
    ['id' => 20, 'name' => 'Land Rover', 'imageURL' => 'assets/img/brand-imgs/Land_Rover.png'],
    ['id' => 21, 'name' => 'Lexus', 'imageURL' => 'assets/img/brand-imgs/Lexus.png'],
    ['id' => 22, 'name' => 'Maserati', 'imageURL' => 'assets/img/brand-imgs/Maserati.png'],
    ['id' => 23, 'name' => 'Mazda', 'imageURL' => 'assets/img/brand-imgs/Mazda.png'],
    ['id' => 24, 'name' => 'Mercedes-Benz', 'imageURL' => 'assets/img/brand-imgs/Mercedes-Benz.png'],
    ['id' => 25, 'name' => 'MINI', 'imageURL' => 'assets/img/brand-imgs/MINI.png'],
    ['id' => 26, 'name' => 'Mitsubishi', 'imageURL' => 'assets/img/brand-imgs/Mitsubishi.png'],
    ['id' => 27, 'name' => 'Nissan', 'imageURL' => 'assets/img/brand-imgs/Nissan.png'],
    ['id' => 29, 'name' => 'Porsche', 'imageURL' => 'assets/img/brand-imgs/Porsche.png'],
    ['id' => 30, 'name' => 'Ram', 'imageURL' => 'assets/img/brand-imgs/Ram.png'],
    ['id' => 31, 'name' => 'Subaru', 'imageURL' => 'assets/img/brand-imgs/Subaru.png'],
    ['id' => 32, 'name' => 'Toyota', 'imageURL' => 'assets/img/brand-imgs/Toyota.png'],
    ['id' => 33, 'name' => 'VinFast', 'imageURL' => 'assets/img/brand-imgs/VinFast.png'],
    ['id' => 34, 'name' => 'Volkswagen', 'imageURL' => 'assets/img/brand-imgs/Volkswagen.png'],
    ['id' => 35, 'name' => 'Volvo', 'imageURL' => 'assets/img/brand-imgs/Volvo.png'],
];

$showUsedCars = [
    ['id' => 1, 'name' => 'Acura', 'imageURL' => 'assets/img/brand-imgs/Acura.png'],
    ['id' => 2, 'name' => 'Alfa Romeo', 'imageURL' => 'assets/img/brand-imgs/Alfa_Romeo.png'],
    ['id' => 3, 'name' => 'Audi', 'imageURL' => 'assets/img/brand-imgs/Audi.png'],
    ['id' => 4, 'name' => 'Bentley', 'imageURL' => 'assets/img/brand-imgs/Bentley.png'],
    ['id' => 5, 'name' => 'BMW', 'imageURL' => 'assets/img/brand-imgs/BMW.png'],
    ['id' => 5, 'name' => 'Buick', 'imageURL' => 'assets/img/brand-imgs/Buick.png'],
    ['id' => 6, 'name' => 'Cadillac', 'imageURL' => 'assets/img/brand-imgs/Cadillac.png'],
    ['id' => 7, 'name' => 'Chevrolet', 'imageURL' => 'assets/img/brand-imgs/Chevrolet.png'],
    ['id' => 8, 'name' => 'Chrysler', 'imageURL' => 'assets/img/brand-imgs/Chrysler.png'],
    ['id' => 9, 'name' => 'Dodge', 'imageURL' => 'assets/img/brand-imgs/Dodge.png'],
    ['id' => 10, 'name' => 'FIAT', 'imageURL' => 'assets/img/brand-imgs/FIAT.png'],
    ['id' => 11, 'name' => 'Ford', 'imageURL' => 'assets/img/brand-imgs/Ford.png'],
    ['id' => 12, 'name' => 'Genesis', 'imageURL' => 'assets/img/brand-imgs/Genesis.png'],
    ['id' => 13, 'name' => 'GMC', 'imageURL' => 'assets/img/brand-imgs/GMC.png'],
    ['id' => 14, 'name' => 'Honda', 'imageURL' => 'assets/img/brand-imgs/Honda.png'],
    ['id' => 15, 'name' => 'Hyundai', 'imageURL' => 'assets/img/brand-imgs/Hyundai.png'],
    ['id' => 16, 'name' => 'INFINITI', 'imageURL' => 'assets/img/brand-imgs/INFINITI.png'],
    ['id' => 17, 'name' => 'Jaguar', 'imageURL' => 'assets/img/brand-imgs/Jaguar.png'],
    ['id' => 18, 'name' => 'Jeep', 'imageURL' => 'assets/img/brand-imgs/Jeep.png'],
    ['id' => 19, 'name' => 'Kia', 'imageURL' => 'assets/img/brand-imgs/Kia.png'],
    ['id' => 20, 'name' => 'Land Rover', 'imageURL' => 'assets/img/brand-imgs/Land_Rover.png'],
    ['id' => 21, 'name' => 'Lexus', 'imageURL' => 'assets/img/brand-imgs/Lexus.png'],
    ['id' => 22, 'name' => 'Lincoln', 'imageURL' => 'assets/img/brand-imgs/Lincoln.png'],
    ['id' => 23, 'name' => 'Lotus', 'imageURL' => 'assets/img/brand-imgs/Lotus.png'],
    ['id' => 24, 'name' => 'Lucid', 'imageURL' => 'assets/img/brand-imgs/Lucid.png'],
    ['id' => 25, 'name' => 'Maserati', 'imageURL' => 'assets/img/brand-imgs/Maserati.png'],
    ['id' => 26, 'name' => 'Maybach', 'imageURL' => 'assets/img/brand-imgs/Maybach.png'],
    ['id' => 27, 'name' => 'Mazda', 'imageURL' => 'assets/img/brand-imgs/Mazda.png'],
    ['id' => 28, 'name' => 'McLaren', 'imageURL' => 'assets/img/brand-imgs/McLaren.png'],
    ['id' => 29, 'name' => 'Mercedes-Benz', 'imageURL' => 'assets/img/brand-imgs/Mercedes-Benz.png'],
    ['id' => 30, 'name' => 'Mercury', 'imageURL' => 'assets/img/brand-imgs/Mercury.png'],
    ['id' => 31, 'name' => 'MINI', 'imageURL' => 'assets/img/brand-imgs/MINI.png'],
    ['id' => 32, 'name' => 'Mitsubishi', 'imageURL' => 'assets/img/brand-imgs/Mitsubishi.png'],
    ['id' => 33, 'name' => 'Nissan', 'imageURL' => 'assets/img/brand-imgs/Nissan.png'],
    ['id' => 34, 'name' => 'Oldsmobile', 'imageURL' => 'assets/img/brand-imgs/Oldsmobile.png'],
    ['id' => 35, 'name' => 'Panoz', 'imageURL' => 'assets/img/brand-imgs/Panoz.png'],
    ['id' => 36, 'name' => 'Plymouth', 'imageURL' => 'assets/img/brand-imgs/Plymouth.png'],
    ['id' => 37, 'name' => 'Polestar', 'imageURL' => 'assets/img/brand-imgs/Polestar.png'],
    ['id' => 38, 'name' => 'Pontiac', 'imageURL' => 'assets/img/brand-imgs/Pontiac.png'],
    ['id' => 39, 'name' => 'Porsche', 'imageURL' => 'assets/img/brand-imgs/Porsche.png'],
    ['id' => 40, 'name' => 'Ram', 'imageURL' => 'assets/img/brand-imgs/Ram.png'],
    ['id' => 41, 'name' => 'Rivian', 'imageURL' => 'assets/img/brand-imgs/Rivian.png'],
    ['id' => 42, 'name' => 'Rolls-Royce', 'imageURL' => 'assets/img/brand-imgs/Rolls-Royce.png'],
    ['id' => 43, 'name' => 'Saab', 'imageURL' => 'assets/img/brand-imgs/Saab.png'],
    ['id' => 44, 'name' => 'Saturn', 'imageURL' => 'assets/img/brand-imgs/Saturn.png'],
    ['id' => 45, 'name' => 'Scion', 'imageURL' => 'assets/img/brand-imgs/Scion.png'],
    ['id' => 46, 'name' => 'smart', 'imageURL' => 'assets/img/brand-imgs/smart.png'],
    ['id' => 47, 'name' => 'Subaru', 'imageURL' => 'assets/img/brand-imgs/Subaru.png'],
    ['id' => 48, 'name' => 'Toyota', 'imageURL' => 'assets/img/brand-imgs/Toyota.png'],
    ['id' => 49, 'name' => 'VinFast', 'imageURL' => 'assets/img/brand-imgs/VinFast.png'],
    ['id' => 50, 'name' => 'Volkswagen', 'imageURL' => 'assets/img/brand-imgs/Volkswagen.png'],
    ['id' => 51, 'name' => 'Volvo', 'imageURL' => 'assets/img/brand-imgs/Volvo.png'],
]
?>


